#!/usr/bin/env bash

set -eu

clone() {
  local repo="$1" branch="$2" dest="$3"

  if [ -d "$dest" ]; then
    echo "  - Found $repo at $dest, not cloning..." >&2
    return 0
  fi

  echo "  - Cloning $repo $branch to $dest..." >&2

  git clone --quiet \
    --depth 1 \
    --no-single-branch \
    --branch "$branch" \
    "https://github.com/bats-core/$repo.git" "$dest" 2> /dev/null || {
      echo "  - Couldn't clone $repo" >&2
      return 1
    }
}

echo "Setting up test environment..."

clone bats-core    v1.3.0 test/bats
clone bats-support master test/test_helper/bats-support
clone bats-assert  master test/test_helper/bats-assert
