name: Tests

on: [push]

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: |
          make test-shellcheck

  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run bats tests on Ubuntu
        shell: 'script -q -e -c "bash {0}"'
        env:
          TERM: linux
        run: |
          bash --version
          make test-bats

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Run bats tests on Windows
        run: |
          bash --version
          # make test-bats
          bash -c "time BATS_NO_PARALLELIZE_ACROSS_FILES=1 BATS_NUMBER_OF_PARALLEL_JOBS=2 ./test/bats/bin/bats --formatter tap test"

  # macos:
  #   runs-on: macos-11
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install unbuffer via expect
  #       run: brew install expect
  #     - name: Run bats tests on macOS
  #       shell: 'unbuffer bash {0}'
  #       env:
  #         TERM: linux
  #       run: |
  #         bash --version
  #         make test-bats
